# Generated by Django 3.0.5 on 2024-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examsession_proctoringevent_suspiciousactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
