# Generated by Django 3.0.5 on 2024-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('question_number', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('duration_minutes', models.IntegerField(default=60)),
            ],
        ),
    ]
