# Generated by Django 3.0.5 on 2024-08-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
